//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pravoslavni_Crkveni_Kalendar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pravoslavni_Crkveni_Kalendar.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the program.
        /// </summary>
        public static string AboutButton {
            get {
                return ResourceManager.GetString("AboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian-Orthodox Church Calendar.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Annunciation is the day when the Archangel Gabriel appeared to the Mother of God and told her that, through the Holy Spirit, she was in a blessed state and that she would give birth to a son..
        /// </summary>
        public static string BlagovestiDesc {
            get {
                return ResourceManager.GetString("BlagovestiDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the biggest Christian holidays of the Virgin Mary, celebrated every August 28, is marked with a red letter and represents the holiday of mothers and children..
        /// </summary>
        public static string BogorodiceDesc {
            get {
                return ResourceManager.GetString("BogorodiceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy handmade icon.
        /// </summary>
        public static string BuyButton {
            get {
                return ResourceManager.GetString("BuyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionTitle {
            get {
                return ResourceManager.GetString("DescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today marks the restoration of the temple of the Great Martyr George in Lydia and the transfer of the relics of Saint George to that temple.
        ///
        ///An icon is used for Đurđić, which shows a soldier standing in a field with a spear in his hand..
        /// </summary>
        public static string DurdicDesc {
            get {
                return ResourceManager.GetString("DurdicDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John was born six months before Jesus Christ, to father Zachary and mother Elizabeth, who were quite old at that time. According to tradition, the Archangel Gabriel appeared to the high priest Zachary in the Jerusalem temple and before announcing the conception of the virgin (the birth of Jesus Christ). he announced the conception of old Jelisaveta..
        /// </summary>
        public static string KrstiteljaDesc {
            get {
                return ResourceManager.GetString("KrstiteljaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Whoever is baptized with a cross, fasts on the Day of the Cross.&quot; that&apos;s what our people say. Two events are celebrated on this day..
        /// </summary>
        public static string KrstovdanDesc {
            get {
                return ResourceManager.GetString("KrstovdanDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageTitle {
            get {
                return ResourceManager.GetString("LanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lazarus Saturday or Vrbica is prepared in the last week of Lent, for the biggest Christian holiday - Easter..
        /// </summary>
        public static string LazarevaSubotaDesc {
            get {
                return ResourceManager.GetString("LazarevaSubotaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feast of Saint Martyr Marina is popularly known as Fiery Mary.
        ///St. Marina was a great fighter for the Christian faith and the protection of women. People believe that St. Marina burns and punishes with fire, so she belongs to the &quot;fiery&quot; saints like St. Elijah..
        /// </summary>
        public static string MarinaDesc {
            get {
                return ResourceManager.GetString("MarinaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version found!.
        /// </summary>
        public static string NewVersionCaption {
            get {
                return ResourceManager.GetString("NewVersionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A version of this application exists, that is newer than the current one. Would you like to update?.
        /// </summary>
        public static string NewVersionText {
            get {
                return ResourceManager.GetString("NewVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this day, the Orthodox Church and believers celebrate the Day of the Holy Apostles Peter and Paul, a holiday that is known in our people by the name - Peter&apos;s Day..
        /// </summary>
        public static string PavlovdanDesc {
            get {
                return ResourceManager.GetString("PavlovdanDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After three years of his preaching, Jesus Christ led his apostles James, Peter and John to Mount Tavor. During the following night, Jesus Christ was transformed in front of the apostles and became light..
        /// </summary>
        public static string PreobrazenjeDesc {
            get {
                return ResourceManager.GetString("PreobrazenjeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specific event that is commemorated and celebrated on that day happened according to Christian belief on October 1, 911, during the time of Emperor Leo the Wise (or the Philosopher). An all-night vigil was held in the Church of the Virgin Mary in Constantinople..
        /// </summary>
        public static string PresveteBogorodiceDesc {
            get {
                return ResourceManager.GetString("PresveteBogorodiceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mala Gospojina is a national holiday that celebrates the birth of the Virgin Mary. Many customs are associated with this holiday, and it is especially celebrated and respected by women..
        /// </summary>
        public static string RodjenjeDesc {
            get {
                return ResourceManager.GetString("RodjenjeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The holiday on which the day of Saints Sergius and Bacchus is celebrated in our nation is called Srđevdan.
        ///
        ///Because of their Christian faith, Bacchus and Sergius were executed as Roman dignitaries at the court of Emperor Maximilian because they refused to bow down to the Roman gods..
        /// </summary>
        public static string SrdevdanDesc {
            get {
                return ResourceManager.GetString("SrdevdanDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She was born two millennia ago in the city of Magdala (Syria), after which she got her last name.
        ///According to tradition, Mary Magdalene was a sinner in her youth whom Jesus Christ saved from stoning..
        /// </summary>
        public static string SvetaMarijaDesc {
            get {
                return ResourceManager.GetString("SvetaMarijaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Serbia, our people often confuse Holy Friday Trnova (August 8) with Holy Friday (October 27).
        ///
        ///The two saints are distinguished on the icons by the symbol of Saint Petka Trnova, the patroness of the blind, who holds a tablet with carved eyes in her hands..
        /// </summary>
        public static string SvetaParaskevaDesc {
            get {
                return ResourceManager.GetString("SvetaParaskevaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sveta Petka.
        /// </summary>
        public static string SvetaPetkaDesc {
            get {
                return ResourceManager.GetString("SvetaPetkaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olympias was born in 522, and as a child he was given to the service of God.
        ///He served as a deacon of the Andrianapolitan bishop Theodore and learned the Holy Scriptures with him.
        ///Saint Olympias always tried to find ways to be alone, he always wanted to spend his life in prayer in solitude..
        /// </summary>
        public static string SvetiAlimpijeDesc {
            get {
                return ResourceManager.GetString("SvetiAlimpijeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peter was sleeping in prison, chained between two soldiers, and the night before he was brought to court, an angel woke him up and said to him: &quot;Get up, put on your clothes and gird yourself, then come with me.&quot;.
        /// </summary>
        public static string SvetiApostolPetarDesc {
            get {
                return ResourceManager.GetString("SvetiApostolPetarDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Michael the Taxiarch is an archangel in Judaism, Christianity, Islam, and the Baha&apos;i faith..
        /// </summary>
        public static string SvetiArandjelDesc {
            get {
                return ResourceManager.GetString("SvetiArandjelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In our nation, Mitrovdan represents one of the five greatest Serbian holidays.
        ///
        ///This holiday is dedicated to the ancient commander Demetrius of Thessaloniki, who lost his life for the sake of the spread of Christianity..
        /// </summary>
        public static string SvetiDimitrijeDesc {
            get {
                return ResourceManager.GetString("SvetiDimitrijeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feast of Saint George, one of the nine great martyrs and the first martyrs for the Christian faith, is celebrated in all temples of the Serbian Orthodox Church and is one of the most common celebrations of Orthodox Serbs..
        /// </summary>
        public static string SvetiGeorgijeDesc {
            get {
                return ResourceManager.GetString("SvetiGeorgijeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On March 22, Mladenci is celebrated. They are dedicated to the memory of the forty Martyrs of Sevasti, who died for the faith of Christ in the year 320..
        /// </summary>
        public static string Svetih40mucenikaDesc {
            get {
                return ResourceManager.GetString("Svetih40mucenikaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January 2 according to the modern calendar (December 20 according to the church calendar) is the feast of the baptism of Saint Ignatius the God-Bearer..
        /// </summary>
        public static string SvetiIgnjatijeDesc {
            get {
                return ResourceManager.GetString("SvetiIgnjatijeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Elijah is present in the Old and New Testaments as a prophet whose characteristics were taken over by Christianity, connecting him with the emergence of a new faith and the new coming of Christ..
        /// </summary>
        public static string SvetiIlijaDesc {
            get {
                return ResourceManager.GetString("SvetiIlijaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to St. John is a model of honesty and righteousness, so in the Serbian people there is a custom that on Midsummer&apos;s Day people become brothers and godfathers &quot;after God and St. John&quot;. Orthodox Christians celebrate the feast of the baptism of St. John, which is in third place in terms of the number of priests who celebrate, on January 20..
        /// </summary>
        public static string SvetiJovanDesc {
            get {
                return ResourceManager.GetString("SvetiJovanDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Michaelmas Day is a day dedicated to Saint Cyriacus the Hermit, popularly known as Saint Michael. There is a belief that the real autumn comes only after this holiday..
        /// </summary>
        public static string SvetiKirijakDesc {
            get {
                return ResourceManager.GetString("SvetiKirijakDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On June 28, the Orthodox Church and its believers celebrate Vidovdan, known as the date when the Battle of Kosovo took place and the feast of the holy martyrs Vid and Lazar Hrebeljanović..
        /// </summary>
        public static string SvetiKnezLazarDesc {
            get {
                return ResourceManager.GetString("SvetiKnezLazarDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christianity also teaches that he is the author of the third Gospel of the New Testament, around the year 60. He accompanied the apostle Paul on his missionary journeys, and later he preached himself.
        /// </summary>
        public static string SvetiLukaDesc {
            get {
                return ResourceManager.GetString("SvetiLukaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On that day, Saint Mark was executed in Egypt during the service of the liturgy in the Church of Alexandria. Saint Mark is one of the apostles (disciples) of Jesus Christ and the author of the second gospel..
        /// </summary>
        public static string SvetiMarkoDesc {
            get {
                return ResourceManager.GetString("SvetiMarkoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In our nation, Mitrovdan represents one of the five greatest Serbian holidays.
        ///
        ///This holiday is dedicated to the ancient commander Demetrius of Thessaloniki, who lost his life for the sake of the spread of Christianity..
        /// </summary>
        public static string SvetiNektarijeDesc {
            get {
                return ResourceManager.GetString("SvetiNektarijeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Nicholas or Nicholas Day, the most common holiday in Serbia, is celebrated on December 19, the day this saint died in 345 AD. They say that half of Serbia celebrates Saint Nicholas, and the other half goes to visit..
        /// </summary>
        public static string SvetiNikolaDesc {
            get {
                return ResourceManager.GetString("SvetiNikolaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Panteleimon or Saint Pantelia was born in Nicomedia. As a young man, he studied medicine and devoted himself to faith and Christ. There are many records of his miraculous healings..
        /// </summary>
        public static string SvetiPanteljmonDesc {
            get {
                return ResourceManager.GetString("SvetiPanteljmonDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stefan Dečanski is one of the most tragic figures in the Nemanjić lineage.
        ///His tragic fate began in his youth when his father Milutin blinded him and sent him to prison in Constantinople.
        ///According to tradition and church teaching, after five years, Saint Nicholas restored King Stephen&apos;s sight..
        /// </summary>
        public static string SvetiStefanDecanskiDesc {
            get {
                return ResourceManager.GetString("SvetiStefanDecanskiDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This day is also celebrated as the third day of Christmas for those who do not celebrate it. According to tradition, Stefan was the first of the seven deacons who were ordained by the holy apostles and appointed to serve the poor in Jerusalem. That is why he was called an archdeacon..
        /// </summary>
        public static string SvetiStefanDesc {
            get {
                return ResourceManager.GetString("SvetiStefanDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularly known as &quot;Unfaithful Thomas&quot; because he refused to believe in the resurrection of Jesus Christ until he saw him himself and touched his nail wounds and put his hands in his ribs..
        /// </summary>
        public static string SvetiTomaDesc {
            get {
                return ResourceManager.GetString("SvetiTomaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Serbian Orthodox Church of St. Trifun celebrates February 14 according to the new calendar, or February 1 according to the old calendar. It is celebrated as the &quot;Day of Love and Wine&quot;..
        /// </summary>
        public static string SvetiTrifunDesc {
            get {
                return ResourceManager.GetString("SvetiTrifunDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Holy Three Hierarchs are Saints Basil the Great, Gregory the Theologian and John Chrysostom, and each of them has its own day of celebration in the month of January..
        /// </summary>
        public static string SvetiTriJerarhaDesc {
            get {
                return ResourceManager.GetString("SvetiTriJerarhaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today, the Serbian Orthodox Church and believers celebrate the feast of St. Basil of Ostrog, who is also called the Miracle Worker because of the healing powers of his relics and holy prayers..
        /// </summary>
        public static string SvetiVasilijeDesc {
            get {
                return ResourceManager.GetString("SvetiVasilijeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January 4th is the date of honoring Saint Basil, the Great Archbishop of Caesarea who was born around 329 during the reign of Emperor Constantine..
        /// </summary>
        public static string SvetiVasilijeVelikiDesc {
            get {
                return ResourceManager.GetString("SvetiVasilijeVelikiDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He was known as the Enlightener, was a Serbian prince and Orthodox monk, the first Archbishop of the autocephalous Serbian Church, the founder of Serbian law, and a diplomat..
        /// </summary>
        public static string SvetogSaveDesc {
            get {
                return ResourceManager.GetString("SvetogSaveDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string ToolTipGerman {
            get {
                return ResourceManager.GetString("ToolTipGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbocroatian.
        /// </summary>
        public static string ToolTipSerboCroatian {
            get {
                return ResourceManager.GetString("ToolTipSerboCroatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to St. John is known as someone who first announced the arrival of Jesus Christ on earth, and after his arrival baptized him in the Jordan River..
        /// </summary>
        public static string UsekovanjeDesc {
            get {
                return ResourceManager.GetString("UsekovanjeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this day, the memory of the first entry of the Virgin into the temple of God, accompanied by her parents Joachim and Anna, is celebrated.
        ///Namely, Maria was brought to the temple as a three-year-old child in accordance with her parents&apos; vow that if they gave birth, they would hand over the child to God in the temple.
        ///In the festive procession, Maria walked between her mother and father, and many relatives and friends were moving behind them..
        /// </summary>
        public static string VavedenjeDesc {
            get {
                return ResourceManager.GetString("VavedenjeDesc", resourceCulture);
            }
        }
    }
}
